name: Sync Wiki Citations to Zotero

# When should this automation run?
on:
  # Run every day at 6 AM UTC
  schedule:
    - cron: '0 6 * * *'
  
  # Also allow manual running
  workflow_dispatch:
  
  # Run when the script is updated
  push:
    paths:
      - 'wiki_sync.py'
      - '.github/workflows/sync-citations.yml'

jobs:
  sync-citations:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the files from your repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Step 3: Install required tools
    - name: Install dependencies
      run: |
        pip install requests
    
    # Step 4: Run the wiki citation sync with Zotero API
    - name: Run automated Zotero sync
      env:
        ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
        ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
      run: |
        python wiki_sync.py
    
    # Step 5: Save any changes back to your repository
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add references.bib
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-sync: Updated references.bib from Zotero after wiki sync"
          git push
        fi
    
    # Step 6: Create a summary of what happened
    - name: Create sync summary
      run: |
        echo "## Sync Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Workflow completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "- Check the logs above for details on new citations added" >> $GITHUB_STEP_SUMMARY
        echo "- Updated references.bib file is now available in the repository" >> $GITHUB_STEP_SUMMARY
